# Generated by Django 4.2.3 on 2023-08-12 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.CharField(max_length=200, null=True)),
                ('espace', models.IntegerField(default=0)),
                ('proprete', models.IntegerField(default=0)),
                ('localisation', models.IntegerField(default=0)),
                ('prix', models.IntegerField(default=0)),
                ('service', models.IntegerField(default=0)),
                ('nom_parent', models.CharField(max_length=200, null=True)),
                ('email_parent', models.CharField(max_length=200, null=True)),
                ('tel_parent', models.CharField(max_length=200)),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jardin_avis', to='jardins.jardin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
