# Generated by Django 4.2.3 on 2023-08-26 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0003_avis_nb_etoiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='mdp',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
