# Generated by Django 4.2.3 on 2023-08-26 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jardins', '0004_proprietaire_mdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jardin',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
